// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProfilesService.Infrastructure.Database;

#nullable disable

namespace ProfilesService.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ProfilesDbContext))]
    [Migration("20260225174524_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProfilesService.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("ProfilesService.Domain.Entities.OrganizationMember", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("organization_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.HasKey("MemberId", "organization_id");

                    b.HasIndex("organization_id");

                    b.ToTable("OrganizationMember");
                });

            modelBuilder.Entity("ProfilesService.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("ProfilesService.Domain.Entities.Organization", b =>
                {
                    b.OwnsOne("ProfilesService.Domain.ValueObjects.ImageRef", "Image", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Link")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("image_link");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("Organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.OwnsOne("ProfilesService.Domain.ValueObjects.OrganizationInformation", "Information", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("email");

                            b1.Property<bool>("IsPublic")
                                .HasColumnType("boolean")
                                .HasColumnName("is_public");

                            b1.Property<string>("OrganizationName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("organization_name");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("Organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.Navigation("Image");

                    b.Navigation("Information")
                        .IsRequired();
                });

            modelBuilder.Entity("ProfilesService.Domain.Entities.OrganizationMember", b =>
                {
                    b.HasOne("ProfilesService.Domain.Entities.UserProfile", "MemberNavigation")
                        .WithMany("OrganizationMembersNavigation")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProfilesService.Domain.Entities.Organization", "OrganizationNavigation")
                        .WithMany("OrganizationMembers")
                        .HasForeignKey("organization_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemberNavigation");

                    b.Navigation("OrganizationNavigation");
                });

            modelBuilder.Entity("ProfilesService.Domain.Entities.UserProfile", b =>
                {
                    b.OwnsOne("ProfilesService.Domain.ValueObjects.ImageRef", "Image", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Link")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("image_link");

                            b1.HasKey("UserProfileId");

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.OwnsOne("ProfilesService.Domain.ValueObjects.UserPersonalInformation", "PersonalInformation", b1 =>
                        {
                            b1.Property<Guid>("UserProfileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("last_name");

                            b1.Property<string>("ShownUserName")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("shown_name");

                            b1.HasKey("UserProfileId");

                            b1.HasIndex("ShownUserName")
                                .IsUnique();

                            b1.ToTable("Profiles");

                            b1.WithOwner()
                                .HasForeignKey("UserProfileId");
                        });

                    b.Navigation("Image");

                    b.Navigation("PersonalInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("ProfilesService.Domain.Entities.Organization", b =>
                {
                    b.Navigation("OrganizationMembers");
                });

            modelBuilder.Entity("ProfilesService.Domain.Entities.UserProfile", b =>
                {
                    b.Navigation("OrganizationMembersNavigation");
                });
#pragma warning restore 612, 618
        }
    }
}
